# Generated by Django 4.2.7 on 2023-11-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TELECOM', '0003_ourservices_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservices',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='origin',
        ),
        migrations.AddField(
            model_name='ourservices',
            name='providercontact',
            field=models.IntegerField(default=12),
        ),
    ]
