# Generated by Django 4.2.7 on 2023-11-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TELECOM', '0004_remove_ourservices_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
