# Generated by Django 4.2.7 on 2023-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TELECOM', '0005_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('contact', models.IntegerField(default=12)),
                ('position', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
